In [1]:
import numpy as np


arr = [1,2,3,4]
print(type(arr))  #list

n_arr = np.array(arr)
print(type(n_arr))  #'numpy.ndarray

#best:
n_arr2 = np.array([1,2,3,4])


print(n_arr * n_arr2)  #direct multiply, not available for list
#for list we need for loop, and this direct is much fasetr





<class 'list'>
<class 'numpy.ndarray'>
[ 1  4  9 16]


In [31]:
import time


st = time.time()
L = range(10000)
c = [i**2 for i in L]
en = time.time()

print(f"for list :{en-st}")

st = time.time()
L = np.arange(1000)
L**2
en = time.time()

print(f"for nparray :{en-st}")

for list :0.0010981559753417969
for nparray :0.0006096363067626953


In [4]:


#uint32 range: 0 to 2^32 - 1
#signed int32 range: -2^31 to 2^31-1   (reason of 31 instead of 32 in power is because 1 bit is for signedd number)


a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b#wrong output ? why write here only
c_unsigned32 = a - b.astype(np.int64) #correct output
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)


"""Why does a - b give a wrong (large positive) result?
Data Type of a and b:

Both a and b are np.uint32 (unsigned 32-bit integers).
Unsigned Arithmetic in numpy:

When you subtract b from a (both of type np.uint32), numpy performs the operation in the unsigned domain.

If b has larger values than a, the result of a - b under unsigned arithmetic will "wrap around."

For example:
for 2 - 5

2 - 5 = -3  # Signed result
In unsigned 32-bit arithmetic, this wraps around:
-3 + 2^32 = 4294967293

This behavior is expected when working with unsigned integers."""

unsigned c: [-3 -3 -3] int64


'Why does a - b give a wrong (large positive) result?\nData Type of a and b:\n\nBoth a and b are np.uint32 (unsigned 32-bit integers).\nUnsigned Arithmetic in numpy:\n\nWhen you subtract b from a (both of type np.uint32), numpy performs the operation in the unsigned domain.\n\nIf b has larger values than a, the result of a - b under unsigned arithmetic will "wrap around."\n\nFor example:\nfor 2 - 5\n\n2 - 5 = -3  # Signed result\nIn unsigned 32-bit arithmetic, this wraps around:\n-3 + 2^32 = 4294967293\n\nThis behavior is expected when working with unsigned integers.'

In [14]:
np.linspace(2,4,10,dtype = float )

# The advantage of linspace creation function is that you guarantee the number of elements and 
# the starting and end point.  arange(start, stop, step) will not include the value stop.



array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [6]:
#2d array
#eye: identity matrix

z = np.eye(6,7, dtype = np.int32)
z

#diag : numpy.diag(v, k=0)
#: If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.

np.diag([[1,2,3],[2,4,5]],k = 2)  #k is optional, if k = 1, its next diagnoal. better keep it zero
np.diag([1,2,434,6])
np.diag(z)
z

#trace:Sum along diagonals.
np.trace(z)

6

In [17]:
np.vander([1,2,4,5,7],2)
np.vander([1,2,4,5,7],3)
#multiplies previous row ...square, cube ..but if k = 1, itll be [1,1,1,1,1] vertically no matter whats in first parameter

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [16,  4,  1],
       [25,  5,  1],
       [49,  7,  1]])

In [53]:
#3d array
np.ones((2,2,2,2), dtype = np.int32)             #for 2d and 3d and nd unlike above
np.zeros((2,3,9))  #first one (2) is no. of 2d matrix of shape (row =3 and col = 9)




array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [61]:

from numpy.random import default_rng
gg = default_rng(42).random((2,3))     #42 is seed, defaultrng produces numbers from 0 to 1
dq =default_rng(42).random((2,3,2))

print(dq)
print()
print(gg)
print()
print(gg*gg)

[[[0.77395605 0.43887844]
  [0.85859792 0.69736803]
  [0.09417735 0.97562235]]

 [[0.7611397  0.78606431]
  [0.12811363 0.45038594]
  [0.37079802 0.92676499]]]

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]

[[0.59900797 0.19261428 0.73719039]
 [0.48632217 0.00886937 0.95183897]]


In [81]:
#When you assign an array or its elements to a new variable, you have to explicitly numpy.copy 

import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:]
b += 10
print('a =', a, '; b =', b)  #output : a = [11 12  3  4  5  6] ; b = [11 12]    both get modified, because its just a view


a = np.array([1, 2, 3, 4, 5, 6])
c = a[:2].copy()
c += 10
print('a =', a, ';  c =', c)



a = [11 12 13 14 15 16] ; b = [11 12 13 14 15 16]


False

In [75]:
import numpy as np
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [83]:
#slicing

x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print(x.shape)  #(2, 3, 1) 2 blocks of 3*1 matrix
x[1:2]

(2, 3, 1)


array([[[4],
        [5],
        [6]]])

In [101]:
#sadvanced slicing
#1: integer array indexing

x = np.array([1,2,3,4,5,6,7,8,9])
x[np.array([5,6,2])]  #gives elements at 5,6,7th position in x , this is kinda fancy slicing
#o/p: array([6, 7, 3])


#boolean indexing

z = np.arange(4,15)
dd = z > 9
print(z)
print(z[dd])

[ 4  5  6  7  8  9 10 11 12 13 14]
[10 11 12 13 14]


In [ ]:
dic ={'a' : 2, 'b':9}
print(dic)
z = np.array(dic)


{'a': 2, 'b': 9}


IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed