In [12]:
import numpy   #not sufficient to import default rng idk why
from numpy.random import default_rng
print(default_rng(77).random((4,2,3)))

[[[0.78593231 0.55117196 0.2438882 ]
  [0.33445321 0.3186902  0.39015401]]

 [[0.80130068 0.09080164 0.37362439]
  [0.7913229  0.75867146 0.60397504]]

 [[0.13074783 0.35984468 0.87080485]
  [0.97813312 0.70718115 0.16087298]]

 [[0.87852274 0.16189544 0.33938701]
  [0.35322257 0.38815248 0.11597432]]]


In [25]:
xi = numpy.random.rand(5,15)  #try randint
x = numpy.array([2,5,8,9,8,7,88,9,6,0])
keys = numpy.random.choice(x,size = 3, replace = False)
keys

array([6, 0, 9])

In [30]:

xi

array([[7.49772916e-01, 6.92610078e-01, 6.25276170e-01, 3.28667353e-01,
        6.47832036e-01, 3.99071905e-04, 9.88822112e-01, 4.47351529e-01,
        2.48474428e-01, 3.98346495e-01, 4.23948975e-02, 9.61540794e-01,
        2.45704255e-01, 3.45517599e-01, 6.84341621e-01],
       [1.97156448e-01, 9.42603411e-01, 9.73798123e-01, 7.26717334e-01,
        9.92055874e-01, 2.59420515e-01, 2.95844587e-01, 1.70851435e-01,
        1.26651166e-01, 7.19402968e-02, 9.24861175e-01, 3.15731900e-02,
        7.77567629e-01, 9.43115501e-01, 2.75066437e-01],
       [5.14070820e-02, 9.74549017e-01, 4.74786102e-01, 4.89399996e-01,
        2.80047516e-01, 2.97075310e-01, 7.87366193e-01, 7.07563920e-02,
        4.10674943e-01, 2.52276874e-01, 3.13933505e-01, 1.57353272e-01,
        6.66349942e-01, 2.85481394e-02, 8.34493666e-01],
       [7.59165191e-01, 2.79802207e-01, 1.01726666e-01, 7.76852144e-01,
        6.75655645e-01, 4.88614321e-01, 6.34459415e-02, 7.73930737e-01,
        9.39108572e-01, 4.69241385e-0

In [35]:
numpy.random.shuffle(x)  #shuffle works in inplace
x

array([ 6,  0,  8,  8,  7,  2,  9,  5, 88,  9])

In [45]:
A = numpy.eye(2)
B = numpy.diag([8,8])
r = numpy.block([A,B])
cc = numpy.zeros((2,2))
d = numpy.ones((2,2))

g = numpy.block([[A,B],[cc,d]])
g

array([[1., 0., 8., 0.],
       [0., 1., 0., 8.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [51]:
numpy.vstack((A,B,cc))
numpy.hstack((A,B,cc))

array([[1., 0., 8., 0., 0., 0.],
       [0., 1., 0., 8., 0., 0.]])

In [55]:
mat = numpy.eye(3,3)
mat
x = numpy.tile(mat, (2,4)) #  4 mat is col and 2 such row
x

array([[1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.]])

In [58]:
numpy.repeat(mat, 1)
numpy.repeat(mat,3)  #for over sampling in ML from dataset,
#first flattens and then repeats k times

array([1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1.])

In [62]:
go2 = numpy.arange(4*3*2) #just to make repsahe easy
lol = go2.reshape(4,3,2)
lol

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])